"""initial_schema_and_updates

Revision ID: db6a58e8521b
Revises: 
Create Date: 2026-06-30 16:55:52.806864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.core.enums import UserRole, JobType, WorkplaceType, SalaryCurrency, ExperienceLevel, JobStatus, ApplicationStatus

# revision identifiers, used by Alembic.
revision: str = 'db6a58e8521b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create enum types explicitly (safe to re-run thanks to checkfirst=True)
    user_role_enum = sa.Enum(UserRole, name="userrole")
    user_role_enum.create(op.get_bind(), checkfirst=True)

    job_type_enum = sa.Enum(JobType, name="jobtype")
    job_type_enum.create(op.get_bind(), checkfirst=True)

    workplace_type_enum = sa.Enum(WorkplaceType, name="workplacetype")
    workplace_type_enum.create(op.get_bind(), checkfirst=True)

    salary_currency_enum = sa.Enum(SalaryCurrency, name="salarycurrency")
    salary_currency_enum.create(op.get_bind(), checkfirst=True)

    experience_level_enum = sa.Enum(ExperienceLevel, name="experiencelevel")
    experience_level_enum.create(op.get_bind(), checkfirst=True)

    job_status_enum = sa.Enum(JobStatus, name="jobstatus")
    job_status_enum.create(op.get_bind(), checkfirst=True)

    application_status_enum = sa.Enum(ApplicationStatus, name="applicationstatus")
    application_status_enum.create(op.get_bind(), checkfirst=True)

    # 2. Helper to build postgresql.ENUM with create_type=False
    def pg_enum(name: str, *labels: str) -> postgresql.ENUM:
        return postgresql.ENUM(*labels, name=name, create_type=False)

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('employer_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_slug', sa.String(length=200), nullable=False),
    sa.Column('company_description', sa.String(length=5000), nullable=True),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('company_phone', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_document_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('twitter_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_profiles_company_slug'), 'employer_profiles', ['company_slug'], unique=True)
    op.create_index(op.f('ix_employer_profiles_user_id'), 'employer_profiles', ['user_id'], unique=True)
    op.create_table('job_seeker_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.String(length=2000), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('preferred_job_type', pg_enum('jobtype', 'FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP'), nullable=True),
    sa.Column('preferred_workplace_type', pg_enum('workplacetype', 'ONSITE', 'REMOTE', 'HYBRID'), nullable=True),
    sa.Column('preferred_salary_min', sa.Integer(), nullable=True),
    sa.Column('preferred_salary_max', sa.Integer(), nullable=True),
    sa.Column('preferred_salary_currency', pg_enum('salarycurrency', 'NGN', 'USD'), nullable=True),
    sa.Column('is_open_to_remote', sa.Boolean(), nullable=True),
    sa.Column('is_open_to_relocation', sa.Boolean(), nullable=True),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('is_profile_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_seeker_profiles_phone_number'), 'job_seeker_profiles', ['phone_number'], unique=False)
    op.create_index(op.f('ix_job_seeker_profiles_user_id'), 'job_seeker_profiles', ['user_id'], unique=True)
    op.create_table('educations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_seeker_profile_id', sa.String(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=False),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_year IS NULL OR end_year >= start_year', name='chk_education_years'),
    sa.ForeignKeyConstraint(['job_seeker_profile_id'], ['job_seeker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educations_job_seeker_profile_id'), 'educations', ['job_seeker_profile_id'], unique=False)
    op.create_table('job_seeker_skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_seeker_profile_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.CheckConstraint('proficiency_level IS NULL OR (proficiency_level >= 1 AND proficiency_level <= 5)', name='chk_skill_proficiency_range'),
    sa.CheckConstraint('years_of_experience IS NULL OR years_of_experience >= 0', name='chk_skill_years_non_negative'),
    sa.ForeignKeyConstraint(['job_seeker_profile_id'], ['job_seeker_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_seeker_profile_id', 'skill_id', name='uq_job_seeker_skill')
    )
    op.create_index(op.f('ix_job_seeker_skills_job_seeker_profile_id'), 'job_seeker_skills', ['job_seeker_profile_id'], unique=False)
    op.create_index(op.f('ix_job_seeker_skills_skill_id'), 'job_seeker_skills', ['skill_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employer_profile_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('nice_to_have', sa.Text(), nullable=True),
    sa.Column('job_type', pg_enum('jobtype', 'FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP'), nullable=False),
    sa.Column('experience_level', pg_enum('experiencelevel', 'ENTRY', 'MID', 'SENIOR', 'EXECUTIVE'), nullable=False),
    sa.Column('workplace_type', pg_enum('workplacetype', 'ONSITE', 'REMOTE', 'HYBRID'), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('lga', sa.String(length=100), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', pg_enum('salarycurrency', 'NGN', 'USD'), nullable=True),
    sa.Column('is_salary_visible', sa.Boolean(), nullable=True),
    sa.Column('status', pg_enum('jobstatus', 'DRAFT', 'PENDING', 'ACTIVE', 'PAUSED', 'CLOSED', 'EXPIRED', 'REJECTED'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('application_url', sa.String(), nullable=True),
    sa.Column('application_email', sa.String(), nullable=True),
    sa.Column('max_applications', sa.Integer(), nullable=True),
    sa.Column('requires_cover_letter', sa.Boolean(), nullable=True),
    sa.Column('custom_questions', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('application_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at IS NULL OR published_at IS NULL OR expires_at > published_at', name='chk_job_expiry_after_publish'),
    sa.CheckConstraint('max_applications IS NULL OR max_applications >= 1', name='chk_job_max_applications'),
    sa.CheckConstraint('salary_max IS NULL OR salary_min IS NULL OR salary_max >= salary_min', name='chk_job_salary_range'),
    sa.ForeignKeyConstraint(['employer_profile_id'], ['employer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_featured_active', 'jobs', ['is_featured', 'status'], unique=False)
    op.create_index('idx_jobs_state_lga', 'jobs', ['state', 'lga'], unique=False)
    op.create_index('idx_jobs_status_state', 'jobs', ['status', 'state'], unique=False)
    op.create_index('idx_jobs_type_experience', 'jobs', ['job_type', 'experience_level'], unique=False)
    op.create_index(op.f('ix_jobs_employer_profile_id'), 'jobs', ['employer_profile_id'], unique=False)
    op.create_index(op.f('ix_jobs_slug'), 'jobs', ['slug'], unique=True)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('work_experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_seeker_profile_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(is_current = TRUE AND end_date IS NULL) OR (is_current = FALSE AND end_date IS NOT NULL AND end_date >= start_date)', name='chk_work_experience_current_logic'),
    sa.ForeignKeyConstraint(['job_seeker_profile_id'], ['job_seeker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_job_seeker_profile_id'), 'work_experiences', ['job_seeker_profile_id'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('job_seeker_profile_id', sa.String(), nullable=False),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('status', pg_enum('applicationstatus', 'PENDING', 'VIEWED', 'SHORTLISTED', 'REJECTED', 'HIRED'), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shortlisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('hired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_seeker_profile_id'], ['job_seeker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'job_seeker_profile_id', name='uq_one_application_per_job')
    )
    op.create_index(op.f('ix_job_applications_job_id'), 'job_applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_applications_job_seeker_profile_id'), 'job_applications', ['job_seeker_profile_id'], unique=False)
    op.create_table('job_skills',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.add_column('email_verification_tokens', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('email_verification_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('email_verification_tokens', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('email_verification_tokens_token_key'), 'email_verification_tokens', type_='unique')
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.drop_constraint(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'email_verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('email_verification_tokens', 'used')
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('role', pg_enum('userrole', 'JOB_SEEKER', 'EMPLOYER', 'ADMIN', 'SUPERADMIN'), server_default='JOB_SEEKER', nullable=False))
    op.alter_column('users', 'role', server_default=None)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('email_verification_tokens', sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.create_unique_constraint(op.f('email_verification_tokens_token_key'), 'email_verification_tokens', ['token'])
    op.alter_column('email_verification_tokens', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('email_verification_tokens', 'created_at')
    op.drop_column('email_verification_tokens', 'used_at')
    op.create_table('user_profiles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey'))
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_job_applications_job_seeker_profile_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_job_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_work_experiences_job_seeker_profile_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_slug'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_employer_profile_id'), table_name='jobs')
    op.drop_index('idx_jobs_type_experience', table_name='jobs')
    op.drop_index('idx_jobs_status_state', table_name='jobs')
    op.drop_index('idx_jobs_state_lga', table_name='jobs')
    op.drop_index('idx_jobs_featured_active', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_seeker_skills_skill_id'), table_name='job_seeker_skills')
    op.drop_index(op.f('ix_job_seeker_skills_job_seeker_profile_id'), table_name='job_seeker_skills')
    op.drop_table('job_seeker_skills')
    op.drop_index(op.f('ix_educations_job_seeker_profile_id'), table_name='educations')
    op.drop_table('educations')
    op.drop_index(op.f('ix_job_seeker_profiles_user_id'), table_name='job_seeker_profiles')
    op.drop_index(op.f('ix_job_seeker_profiles_phone_number'), table_name='job_seeker_profiles')
    op.drop_table('job_seeker_profiles')
    op.drop_index(op.f('ix_employer_profiles_user_id'), table_name='employer_profiles')
    op.drop_index(op.f('ix_employer_profiles_company_slug'), table_name='employer_profiles')
    op.drop_table('employer_profiles')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ####
    # 2. Drop the custom types cleanly if you ever roll back the migration
    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="jobtype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="workplacetype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="salarycurrency").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="experiencelevel").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="jobstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="applicationstatus").drop(op.get_bind(), checkfirst=True)